language: rust
rust:
  - stable
  - nightly


before_install:
  - export RUSTFLAGS="-D warnings"
  - if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then
    rustup self update &&
    rustup component add rustfmt clippy &&
    cargo clippy --version;
    fi


cache:
  cargo: true
  directories:
    - $HOME/.local/share/

script:
  - if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then
    cargo fmt --all -- --check &&
    cargo clippy --all --tests --examples;
    fi
  - env RUST_BACKTRACE=1 RUST_LOG=headless_chrome=trace cargo test -- --nocapture
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
    cargo test --doc --features nightly README;
    fi