[package]
name = "tokio-i3ipc"
version = "0.1.0"
authors = ["Evan Cameron <cameron.evan@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-reactor = "0.1"
tokio-uds = "0.2"
tokio-codec = "0.1"
tokio = "0.1"
futures = "0.1"
i3ipc-types = { path = "i3ipc-types" }
byteorder = "1.3"

[workspace]
members = ["./", "i3ipc-types"]