[package]
name = "async-i3ipc"
version = "0.1.0"
authors = ["Evan Cameron <cameron.evan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.6.2"
serde = "1.0"
serde_json = "1.0"
i3ipc-types = { path = "../i3ipc-types", features = ["async-std-traits"] }


[[example]]
name = "subscribe"
path = "examples/subscribe.rs"

[[example]]
name = "workspaces"
path = "examples/workspaces.rs"

[[example]]
name = "get_tree"
path = "examples/get_tree.rs"