[package]
name = "i3ipc-types"
version = "0.3.0"
authors = ["Evan Cameron <cameron.evan@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_repr = "0.1"
serde_derive = "1.0"
serde_json = "1.0"